### ISSUE TITLE
Would you accept a DropDatabaseBuffers() function?

### ISSUE THREAD

**Issue by petergeoghegan** [MasaoFujii/pg_cheat_funcs#1]
Hi Fujii-san,

I am thinking about writing a pg_cheat_funcs() patch to call the function DropDatabaseBuffers(). I would use something like this for testing my corruption detection tools. I can modify the on-disk representation myself, possibly by using my pg_hexedit tool, and then call a Postgres function to invalidate anything that happens to be in shared_buffers immediately. I can then test some amcheck function, or whatever it happens to be, to make sure it detects the issue. This new function would be a convenience thing for this very specific kind of work.

I was going to just write a PR, but thought I should ask first: If I wrote a function like this, would you accept it? It's not obvious that you would, because calling DropDatabaseBuffers() outside of something like a DROP DATABASE is generally very dangerous. The function drops dirty buffers without cleaning them/writing them out first. I thought about just making the function do a checkpoint first, which would be easy, but quickly realized that that would be even more dangerous: it would lead to a false sense of security, because it would only work 99% of the time. (There'd still be race conditions)

What do you think? If it's not suitable, I can just do something on my own.

Thanks!

**Comment by MasaoFujii** [comment]
Sorry for the delay. Thanks you for being interested in pg_cheat_funcs!

I'm just writing pg_cheat_funcs as a hobby or for fun, so I'm not sure
what will happen in pg_cheat_funcs. For example, I may get tired of
pg_cheat_funcs and drop its repository tomorrow. This is very extreme
example, though...

Therefore, I think that it's better to add such new function to more
"robust" module or your own one.

Regards,

**Comment by petergeoghegan** [comment]
That's fair. I thought that it might be useful to have potentially-dangerous-but-useful functions like this available in one place for other Postgres hackers. However, an unspoken obligation to maintain it as a real open source project could emerge, and take up a lot of your time.

I may do this myself, since of course there is no reason why it cannot work as a standalone thing.
